### ISSUE TITLE
Exporting namespaces with dots in name breaks it

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#665] opened 2022-12-15 11:08 UTC
## Discussion in forum
https://forum.cortezaproject.org/t/namespace-with-dots-404/830

## TODO
- [ ] create a namespace with a dot in the name
- [ ] export the namespace and see if an error occurs

**Comment by KinyaElGrande** [comment] 2023-01-24 08:35
Could not reproduce the bug.
Exporting a namespace with a dot in the name works as expected.
Closing the issue.

**Closed as completed by KinyaElGrande** 2023-01-24 08:35 UTC
Labels: backend, trivial
