### ISSUE TITLE
Can't copy-paste Tabs block

### ISSUE THREAD

**Issue by bfleming212** [cortezaproject/corteza#1518] opened 2023-11-10 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9

### Current Behavior

I can copy a Tabs Block ("Block has been successfully copied) but can't paste it ("Not a valid page block")

### Expected Behavior

Copy a Tabs Block and then paste it on any other page.

### Steps To Reproduce

Copy Tabs block using copy block feature.
Paste Tabs Block using ⌘-v

**Comment by Fajfa** [comment] 2023-11-10 14:17
Closing, couldn't reproduce.

**Closed as completed by Fajfa** 2023-11-10 14:17 UTC
Labels: frontend
