### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1433] opened 2023-09-12 11:04 UTC
When migrated from an old version (when record values were a separate table), some special characters were not displayed correctly.

For example, having this in values `{"test": ["xoúú"]}` would produce the output of `xoÃºÃº`.

It's worth noting that these values were manually transformed into a reworked storage structure (they did not go through the upgrade/provision flow).

We tried changing the character set/collation but that didn't resolve it.
I guess it's either something in GO or due to JSON decoding (since values are now json encoded).

**Comment by tjerman** [comment] 2023-09-22 11:17
I think the issue is with fastjson (JSON parsing thing we're using). If I dump some data from it:

```
(*fastjson.Value)(0xc001080190)({"test":["xoÃºÃº"]})
(*sql.RawBytes)(0xc00072a048)((len=24 cap=24) {
 00000000  7b 22 74 65 73 74 22 3a  20 5b 22 78 6f c3 83 c2  |{"test": ["xo...|
 00000010  ba c3 83 c2 ba 22 5d 7d                           |....."]}|
})
```

**Comment by tjerman** [comment] 2023-09-22 11:19
If we paste the "special characters" into the front-end and save it like that, it comes out ok:

![Image](https://github.com/cortezaproject/corteza/assets/12545711/d055eba5-c82c-4ccc-821b-032205a65fa5)

But the text in the DB seems off

![Image](https://github.com/cortezaproject/corteza/assets/12545711/0c4a39d6-6995-45ee-aac6-6ca9f5a447e7)

**Comment by tjerman** [comment] 2023-09-22 11:23
Dumping what we get from ^, ths is what I see:

```
(*fastjson.Value)(0xc000f35180)({"test":["xoúú"]})
(*sql.RawBytes)(0xc0001d2810)((len=20 cap=20) {
 00000000  7b 22 74 65 73 74 22 3a  20 5b 22 78 6f c3 ba c3  |{"test": ["xo...|
 00000010  ba 22 5d 7d                                       |."]}|
})
```

**Comment by tjerman** [comment] 2023-09-22 11:31
All that boilerplate stuff is the same between them; the first one has a bunch more unicode stuff to the `c3`.
That's off at the `sql.RawBytes` already so it looks like it's not off with fastjson but rather with SQL

**Comment by tjerman** [comment] 2023-09-22 11:39
Seems to me like I've messed up when constructing those insert statements and not properly encoding those values. Unsure if that's the case and/or how it should be even.

Looking a bit further.

**Comment by tjerman** [comment] 2023-09-22 12:06
Raw bytes from the DB are

```
+------------------------------------+
| HEX(`values`->'$.test[0]')         |
+------------------------------------+
| 22786FC383C2BAC383C2BA202020C3BA22 |
+------------------------------------+
```

(I added one of those characters at the end from the UI `{"test": ["xoúú   �"]}`)

**Comment by tjerman** [comment] 2023-09-22 13:03
Here is the end result:

The issue was caused due to the connection assuming

```
SELECT @@collation_connection;
+------------------------+
| @@collation_connection |
+------------------------+
| latin1_swedish_ci      |
+------------------------+
1 row in set (0.00 sec)
```

So the bytes were off and the CLI wasn't able to show those bytes correctly.
Because of this happening on the CLI side, insertions/alterations via the UI were ok (connection there was specified to be utf8mb4.

Utilizing [this](https://gist.github.com/w0rldart/aa472db45c3817d937a1870a32f77820) I was able to sort it out on my end.

Not sure what we can do here after this has occurred; probably best we just add some notes to the docs. TBD

**Comment by tjerman** [comment] 2023-09-25 09:10
Closing this due to not an issue; resolving affected cases internally.

**Closed as completed by tjerman** 2023-09-25 09:10 UTC
Labels: backend, critical
