### ISSUE TITLE
When I try to clone a block in the page builder, the titles are all linked

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#787] opened 2023-01-16 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When cloning a page block and modifying the title of the cloned block or original block, the title is copied throughout all of the blocks.

### Expected Behavior

Title is saved per block uniquely

### Environment and versions

```markdown
2023.3.0-dev.1
```

### Anything else?

Might be related to https://github.com/cortezaproject/corteza/issues/737

**Comment by Fajfa** [comment] 2023-01-23 13:28
Indeed it was related to #737 
Closing for now since its confirmed fixed

**Closed as completed by Fajfa** 2023-01-23 13:28 UTC

**Comment by skamensky** [comment] 2023-01-23 14:43
Next time a `2023.3.0-dev.1 ` image is released I'll test it as well :-D
