### ISSUE TITLE
Unable to filter checkbox module fields from the record list filter interface

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza#757] opened 2023-01-10 10:08 UTC
## Env

* local dev containerised instance
* v `2022.9.5`
* db: `percona:8.0`

## Bug

Unable to filter checkbox module fields from the record list filter interface.
When I try to filter a checkbox module field, I get a database error.

Filter:

`query: (tasty is true)`

![Image](https://user-images.githubusercontent.com/12545711/211520836-1afb7d3d-e28e-400f-9938-867d9ea1f799.png)

Error:

`"Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)) ORDER BY `compose_record`.`id` ASC LIMIT ?' at line 1"`

![Image](https://user-images.githubusercontent.com/12545711/211520900-4a02f3b8-e189-4d98-b6b8-eaf0cdfdb2cb.png)

**Comment by Bojan-Svirkov** [comment] 2023-01-17 09:55
@tjerman Retested with MySQL and I can confirm that the same error pops up and that the problem is present.

**Comment by tjerman** [comment] 2023-01-18 08:25
2022.9.x monorepo commit `1febba3eb`

**Comment by Bojan-Svirkov** [comment] 2023-01-18 09:31
Retested and confirming that this issue is now fixed. @tjerman The only thing now left is the CL entry.

**Comment by tjerman** [comment] 2023-01-18 10:53
@Bojan-Svirkov can you add a link to this commit/pr in the same entry as you've done it for the other two databases (PGSQL and SQLite had the same issue)

**Closed as completed** 2023-01-18 11:11 UTC
Labels: backend
