### ISSUE TITLE
Number formatting not maintaining the given format

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza#982] opened 2023-03-24 11:53 UTC
## Description of the bug

_Number formatting is not maintained. When I want to use the Indian formatting of a currency 10 million is written like 10,00,00,000.00 But, even setting the formatting in that way, the result is 10,000,000.00 INR._

## Reproduction steps

1.	Go to a module in the admin area
2.	Create a number field
3.	Add in the “Number Input” tab, in the format field the format: 00,00,000.00 (or 00,000.00, which also does not work)
4.	Check out the live example. It will show 10000000 as 10,000,000.00
5.	Extra: 0.000.000 also does not work. And when you say 000.000,00 it will also show as 10,000,000

## Expected behavior 

_The expected behavior is that the format is used. Now we can only use 0,000.00 and nothing else._

## Screenshot/Video

![Image](https://user-images.githubusercontent.com/53232926/227514243-c7989a94-a749-48ef-87df-8f0262d865bc.png)

![Image](https://user-images.githubusercontent.com/53232926/227514253-f4fe6514-3593-42b8-9223-bd7dc3ad7730.png)

![Image](https://user-images.githubusercontent.com/53232926/227514270-cd17cd46-e4cd-434f-823f-bf8e0824bee6.png)

## Version

Branch: 2023.3.0-dev.5.1 
Reporter: Lenny (Test fest)
Browser: Firefox

**Comment by Bojan-Svirkov** [comment] 2023-04-13 09:48
Check whether this is a BE or FE issue.

**Comment by tjerman** [comment] 2023-06-03 10:41
Not a bug. numeral.js doesn't seem to support such a format without explicitly defining your own [formatters](http://numeraljs.com/#custom-formats).
Closing this for now; will open up a discussion when we find the need for this.

**Closed as completed by tjerman** 2023-06-03 10:41 UTC
Labels: backend, frontend
