### ISSUE TITLE
Record revisions: multi-value field tracking doesn't track additions correctly

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#666] opened 2022-12-15 11:14 UTC
## Steps to reproduce
1. I have an `ingredient` multi-value string field
2. I added 3 values (fruit, pineapple, cake) and then edited the thing with adding sprinkles
3. The old column should be fruit, pineapple, and cake while the new column should be sprinkles, fruit, pineapple, cake (I moved the newly added sprinkles to the top)

## Screenshot with values
![Image](https://user-images.githubusercontent.com/85161724/207845034-6932f57c-bfcf-4d3e-b74f-25f6006e9266.png)

**Comment by tjerman** [comment] 2023-01-06 09:14
Server-side everything is fine; the issue is how the data is displayed in the revisions table

**Comment by tjerman** [comment] 2023-01-06 14:57
## Fixed

### What

fixed invalid record revision history for multi value fields.
The first value appeared duplicated, the last value was omitted, and when a value was removed the value was no longer visible in the old version.

### Refs

Monorepo
- 2022.9.x commit `b203224df`

**Comment by Bojan-Svirkov** [comment] 2023-01-09 10:49
Tested and confirming that this now works as expected.

**Closed as completed** 2023-01-09 13:51 UTC
Labels: frontend
