### ISSUE TITLE
Add support for auto-refresh of certain block-types

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#466] opened 2022-11-10 14:14 UTC
# Problem
Compose page blocks do not support auto-content refreshing and this forces users to refresh the browser or navigate away and back to the current page.

# Extending page block configurators
All page block configurators need to be extended to support auto-refresh settings, explicitly enable or disable manual refresh of a block.

Refresh interval can be expressed in seconds and must have lower limit at 5 seconds.

# Page refresh implementation
Since automatic refresh can interfere with user's workflow and can cause data loss, extra protection need to be implemented to prevent that.  

![Image](https://user-images.githubusercontent.com/1500447/198151410-e6bab8d9-2917-4d62-9cc5-e838af3cb6e3.png)

- update 2022.3 Plan #4 @darh

**Comment by EmmyMay** [comment] 2022-11-16 10:19
# Feature Documentation

## Problem
Compose page blocks do not support auto-content refreshing and this forces users to refresh the browser or navigate away and back to the current page.

## What was added
Added auto-refreshing and manual refreshing feature to page blocks excluding, Content, Record and File Blocks. An icon now appears on blocks when you enable the refresh feature. That icon is clickable even though refresh will happen automatically based on the duration you have set.

## Why it was added
To ensure users do not have to refresh the entire page to see new content on blocks.

**Comment by EmmyMay** [comment] 2022-11-16 10:20
https://github.com/cortezaproject/corteza-js/pull/73

https://github.com/cortezaproject/corteza-webapp-compose/pull/446

**Comment by Bojan-Svirkov** [comment] 2022-11-18 11:32
Entry added to the CL

**Comment by Bojan-Svirkov** [comment] 2022-11-18 12:16
@EmmyMay the whole features looks good however I noticed one issue in regards to the record list page block and it's pagination. So the issue is this:

- When I have the auto refresh enabled let's say on 5s and I have record on more than one page, and I am on the second page and after the refresh I am taken on the first page, but the pagination in the footer still says for example 16-20 of 20 records instead of 1-10 of 20 records, and if I click next page I am taken to the next page but the pagination is broken and then it says `31 - 20 of 20 records` but we don't even have 30- records, and after the next refresh if I click next page the pagination is again increased for 10 and it will say 41, then 51 and so on as you can also see on the vide below. @vicpatel  you can also look into this since not sure if this is an issue with pagination or with the page block auto refresh feature.

I will move the ticket to `In progress` so you can double check this.


[a4b09ce8-9e88-447c-b3b7-1da9aa436303.webm](https://user-images.githubusercontent.com/53232926/202703089-39cd4808-b14d-4f1a-b474-19b0e45d5faf.webm)

**Comment by EmmyMay** [comment] 2022-11-18 12:46
Thanks @Bojan-Svirkov I'll look into it

**Comment by EmmyMay** [comment] 2022-11-24 16:35
https://github.com/cortezaproject/corteza/pull/513

@Bojan-Svirkov This should be fixed now. Waiting for @Fajfa to review. Thanks.

**Comment by Bojan-Svirkov** [comment] 2022-11-25 14:50
@EmmyMay This now looks good. I am moving the card to **Done** and once you merge everything you can safely close this issue.

**Closed as completed** 2022-11-28 10:49 UTC
Labels: frontend
